version: "3.9"
name: "video-db-main"
services:
  postgres:
    image: postgres:latest
    container_name: video-db-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: video-db-pg-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
